name: NextJS with Playwright


env:
  CI: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Just checking if we have a CI env
        run: |
          echo "CI variable: $CI" 

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: "20.x"
      - name: Installing deps
        run: npm ci
      - name: Installing playwright browsers
        # --with-deps meaning it will install all libraries, font dependencies, and media codecs 
        run: npx playwright install --with-deps
      - name: Testing E2E
        run: npm run test:e2e
      - name: Building
        run: npm run build:cloudflare
      # - name: Test deploy
      #   run: | 
      #     echo "DONE: Sucessfully uploaded to the server"
      - name: Deploy to the cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}


