name: NextJS with Playwright

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing NodeKs
        uses: actions/setup-node@v4
        with: 
          node-version: "20.x"
      - name: Installing deps
        run: npm ci
      - name: Installing playwright browsers
        run: npm playwright install --with-deps
      - name: Testing E2E
        run: npm run test:e2e
      - name: Building
        run: npm run build
      - name: Test deploy
        run: echo "DONE: Sucessfully uploaded to the server"
        # below is deploying to cloudflare
      # - name: Deploy to the cloudflare
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: {{secrets.MY_CLOUDFLARE_TOKEN}}


