name: Example


on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Installing NodeJS
      uses: actions/setup-node@v4
      with: 
        node-version: "20.x"
    - name: Installing deps
      run: npm ci
    - name: installing playwright with deps
      run: npx playwright install --with-deps
    - name: e2e test
      run: npx playwright test
    - name: build
      run: npm run build
